#消息推送
notice:
  pushdeer:
    url: http://139.198.178.154:8800/message/push?
#消息推送
users:
  yzy:
    key: PDU1Ttmn2KngrRHODOeuVQvU0DkQNgxKshkho
  yao:
    key: PDU1Ttmn2KngrRHODOeuVQvU0DkQNgxKshkho
#定时任务监控
check:
  lukou:
    interval: 60
    list:
      - user: yzy
        keywords:
          - 饮用水
          - 矿泉水
          - 八喜
          - 眼镜
