#路口登录用户
lukou:
  username: username
  password: password
#消息推送
notice:
  pushdeer:
    url: http://localhost:8800/message/push?
#消息推送
users:
  zoyao:
    key: PDU1Ttmn2KngrRHODOeu
  yao:
    key: PDU1Ttmn2KngrRHODOeu
#定时任务监控
check:
  lukou:
    interval: 60
    list:
      - user: zoyao
        keywords:
          - 空调
          - 电视
mairui:
  licence: licence
mysql:
  host: host
  port: port
  user: user
  password: password
  db: db